"""cart_name

Revision ID: 0cfa3121c235
Revises: 19e6fa038ec8
Create Date: 2025-02-19 01:53:32.341687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfa3121c235'
down_revision: Union[str, None] = '19e6fa038ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('products_name', sa.String(), nullable=True))
    op.drop_column('carts', 'product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('product_name', sa.VARCHAR(), nullable=True))
    op.drop_column('carts', 'products_name')
    # ### end Alembic commands ###
