"""delete shit

Revision ID: 69898b1765b4
Revises: b9031732fa4c
Create Date: 2025-03-17 23:19:03.895718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69898b1765b4'
down_revision: Union[str, None] = 'b9031732fa4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM products WHERE name IN ('КАСКО Премиум', 'ОСАГО Базовый', 'Защита дома')")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
