"""Add image_url column to products table

Revision ID: 9e2be42d5d8c
Revises: 69898b1765b4
Create Date: 2025-03-21 21:40:19.777294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2be42d5d8c'
down_revision: Union[str, None] = '69898b1765b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=True))
    product_images = {
        "КАСКО Классика": "/static/images/kasko_1x.png",
        "Практичное КАСКО": "/static/images/kasko2.png",
        "КАСКО Профи": "/static/images/kaskoprof.png",
        "КАСКО Пополам": "/static/images/kaskohalf.png",
        "Всё под контролем": "/static/images/lifeinsu.png",
        "Всё для бизнеса": "/static/images/businsu.png",
    }

    # Обновляем записи в таблице products
    for product_name, image_url in product_images.items():
        op.execute(f"""
            UPDATE products
            SET image_url = '{image_url}'
            WHERE name = '{product_name}';
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.execute("UPDATE products SET image_url = NULL;")
    # ### end Alembic commands ###
